version: "3.9"

services:
  n8n:
    image: docker.io/n8nio/n8n:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Database (values come from .env secrets)
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      # Core runtime configuration (non-secret)
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_HOST: localhost
      N8N_EDITOR_BASE_URL: http://localhost:5678
      WEBHOOK_URL: http://localhost:5678

      # Disable non-essential telemetry / noise
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"

      # Credentials encryption (secret from .env)
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}

      # New-style behavior (non-secret config)
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"        # set "true" if you want to block env access in Code/expressions
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"

    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
